name: 'Yellow Chameleon'
description: 'Synchronize a portion of a repository to match a portion of another repository'
inputs:

  source-path:
    description: 'The path within the source repository to pull content from. Always use a UNIX-style path. (Optional, defaults to root of repository)'
    required: false
    type: string
  destination-repository:
    description: 'The repository to push content to. (Required)'
    required: true
    type: string

  destination-pat:
    description: 'A Personal Authentication Token for the destination-repository. (Required)'
    required: true
    type: string
  destination-pat-username:
    description: 'The username associated with the destination-pat. (Required)'
    required: true
    type: string

  git-name:
    description: 'The name used when creating a commit in the destination-repository. (Required)'
    required: true
    type: string
  git-email:
    description: 'The email used when creating a commit in the destination-repository. (Required)'
    required: true
    type: string

  is-piggybacked:
    description: 'A flag to allow multiple runs in the same worker instance.'
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Clear destination if present
      shell: bash
      run: rm -rf destination
    - name: Checkout Source
      if: ${{ ! inputs.is-piggybacked }}
      uses: actions/checkout@v4
      with:
        path: source
    - name: Check for cached yellow-chameleon binary
      id: check-cache
      if: ${{ ! inputs.is-piggybacked }}
      uses: actions/cache@v4
      with:
        path: yellow-chameleon
        key: ${{ runner.os }}-yellow-chameleon-v0.3
    - name: Download yellow-chameleon binary if not cached
      if: ${{ steps.check-cache.outputs.cache-hit != 'true' && ! inputs.is-piggybacked }}
      uses: robinraju/release-downloader@v1
      with:
        repository: aaronstanek/yellow-chameleon
        tag: v0.3
        fileName: yellow-chameleon
    - name: Set yellow-chameleon binary to be executable
      if: ${{ ! inputs.is-piggybacked }}
      shell: bash
      run: sudo chmod +x yellow-chameleon
    - name: Run yellow-chameleon
      shell: bash
      run: ./yellow-chameleon
      env:
        CAM_SOURCE_PATH: ${{ inputs.source-path }}
        CAM_DEST_REPO: ${{ inputs.destination-repository }}

        CAM_DEST_PAT_SECRET: ${{ inputs.destination-pat }}
        CAM_DEST_PAT_USER: ${{ inputs.destination-pat-username }}

        CAM_GIT_NAME: ${{ inputs.git-name }}
        CAM_GIT_EMAIL: ${{ inputs.git-email }}
